[adgobye]
src.github = "AdGoBye/AdGoBye"
fetch.github = "AdGoBye/AdGoBye"

[adgobye-git]
src.git = "https://github.com/AdGoBye/AdGoBye"
fetch.github = "AdGoBye/AdGoBye"

[alcom]
src.github_tag = "vrc-get/vrc-get"
src.include_regex = "gui-v(.*)"
src.prefix = "gui-v"
fetch.url = "https://github.com/vrc-get/vrc-get/releases/download/gui-v$ver/alcom-$ver-x86_64.AppImage"

[alvr]
src.github = "alvr-org/ALVR"
fetch.github = "alvr-org/ALVR"
git.fetchSubmodules = true

[alvr-git]
src.git = "https://github.com/alvr-org/ALVR"
fetch.github = "alvr-org/ALVR"
git.fetchSubmodules = true

[animdl-git]
src.git = "https://github.com/justfoolingaround/animdl"
fetch.github = "justfoolingaround/animdl"

[gdlauncher-legacy]
src.github = "gorilla-devs/GDLauncher"
fetch.url = "https://github.com/gorilla-devs/GDLauncher/releases/download/$ver/GDLauncher-linux-setup.AppImage"

[gdlauncher-carbon]
src.cmd = "curl https://gdlauncher.com/download/linux | awk 'match($0,/GDLauncher__([0-9]*\\.[0-9]*\\.[0-9]*)/,a){print a[1]}'"
fetch.url = "https://cdn-raw.gdl.gg/launcher/GDLauncher__$ver__linux__x64.AppImage"

[hd2pystratmacro]
src.github = "PassiveLemon/hd2pystratmacro"
fetch.github = "PassiveLemon/hd2pystratmacro"

[hd2pystratmacro-git]
src.git = "https://github.com/PassiveLemon/hd2pystratmacro"
fetch.github = "PassiveLemon/hd2pystratmacro"

[monado-vulkan-layers-git]
src.git = "https://gitlab.freedesktop.org/monado/utilities/vulkan-layers"
fetch.git = "https://gitlab.freedesktop.org/monado/utilities/vulkan-layers.git"

[opencomposite-git]
src.git = "https://gitlab.com/znixian/OpenOVR"
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true

[picom]
src.github = "yshui/picom"
fetch.github = "yshui/picom"

[picom-tag]
src.github_tag = "yshui/picom"
fetch.github = "yshui/picom"

[picom-git]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"

[poepyautopot]
src.github = "PassiveLemon/poepyautopot"
fetch.github = "PassiveLemon/poepyautopot"

[poepyautopot-git]
src.git = "https://github.com/PassiveLemon/poepyautopot"
fetch.github = "PassiveLemon/poepyautopot"

[tilp2-gfm]
src.github_tag = "debrouxl/tilp_and_gfm"
fetch.github = "debrouxl/tilp_and_gfm"

[tilp2-gfm-git]
src.git = "https://github.com/debrouxl/tilp_and_gfm"
fetch.github = "debrouxl/tilp_and_gfm"

[wivrn]
src.github = "WiVRn/WiVRn"
fetch.github = "WiVRn/WiVRn"

[wivrn-monado]
src.cmd = "curl https://api.github.com/repos/WiVRn/WiVRn/releases/latest | jq -r \".tag_name\" | xargs -I {} curl https://raw.githubusercontent.com/WiVRn/WiVRn/{}/CMakeLists.txt | grep GIT_TAG | awk '{print $2}'"
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"

[wivrn-git]
src.git = "https://github.com/WiVRn/WiVRn"
fetch.github = "WiVRn/WiVRn"

[wivrn-git-monado]
src.webpage = "https://github.com/WiVRn/WiVRn/blob/master/CMakeLists.txt"
src.regex = "GIT_TAG\\s*(\\w+)"
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"

