[adgobye]
src.github = "AdGoBye/AdGoBye"
fetch.github = "AdGoBye/AdGoBye"

[adgobye-git]
src.git = "https://github.com/AdGoBye/AdGoBye"
fetch.github = "AdGoBye/AdGoBye"

[alcom]
src.github_tag = "vrc-get/vrc-get"
src.include_regex = "gui-v(.*)"
src.prefix = "gui-v"
fetch.url = "https://github.com/vrc-get/vrc-get/releases/download/gui-v$ver/alcom-$ver-x86_64.AppImage"

[animdl-git]
src.git = "https://github.com/justfoolingaround/animdl"
fetch.github = "justfoolingaround/animdl"

[gdlauncher-legacy]
src.github = "gorilla-devs/GDLauncher"
fetch.url = "https://github.com/gorilla-devs/GDLauncher/releases/download/$ver/GDLauncher-linux-setup.AppImage"

[gdlauncher-carbon]
src.cmd = "curl https://gdlauncher.com/download/linux | awk 'match($0,/GDLauncher__([0-9]*\\.[0-9]*\\.[0-9]*)/,a){print a[1]}'"
fetch.url = "https://cdn-raw.gdl.gg/launcher/GDLauncher__$ver__linux__x64.AppImage"

[hd2pystratmacro]
src.github = "PassiveLemon/hd2pystratmacro"
fetch.github = "PassiveLemon/hd2pystratmacro"

[hd2pystratmacro-git]
src.git = "https://github.com/PassiveLemon/hd2pystratmacro"
fetch.github = "PassiveLemon/hd2pystratmacro"

[lua-pam-git]
src.git = "https://github.com/RMTT/lua-pam"
fetch.github = "RMTT/lua-pam"

[monado-vulkan-layers-git]
src.git = "https://gitlab.freedesktop.org/monado/utilities/vulkan-layers"
fetch.git = "https://gitlab.freedesktop.org/monado/utilities/vulkan-layers.git"

[nimpad]
src.github = "PassiveLemon/nimpad"
fetch.github = "PassiveLemon/nimpad"

[nimpad-git]
src.git = "https://github.com/PassiveLemon/nimpad"
fetch.github = "PassiveLemon/nimpad"

[opencomposite-git]
src.git = "https://gitlab.com/znixian/OpenOVR"
fetch.git = "https://gitlab.com/znixian/OpenOVR.git"
git.fetchSubmodules = true

[picom]
src.github = "yshui/picom"
fetch.github = "yshui/picom"

[picom-tag]
src.github_tag = "yshui/picom"
fetch.github = "yshui/picom"

[picom-git]
src.git = "https://github.com/yshui/picom"
fetch.github = "yshui/picom"

[poepyautopot]
src.github = "PassiveLemon/poepyautopot"
fetch.github = "PassiveLemon/poepyautopot"

[poepyautopot-git]
src.git = "https://github.com/PassiveLemon/poepyautopot"
fetch.github = "PassiveLemon/poepyautopot"

[proton-ge-rtsp]
src.github = "SpookySkeletons/proton-ge-rtsp"
fetch.tarball = "https://github.com/SpookySkeletons/proton-ge-rtsp/releases/download/$ver/$ver.tar.gz"

[tilp2-gfm]
src.github_tag = "debrouxl/tilp_and_gfm"
fetch.github = "debrouxl/tilp_and_gfm"

[tilp2-gfm-git]
src.git = "https://github.com/debrouxl/tilp_and_gfm"
fetch.github = "debrouxl/tilp_and_gfm"

[vapor-git]
src.git = "https://github.com/micheal65536/VapoR"
fetch.github = "micheal65536/VapoR"

[wayvr-dashboard]
src.github = "olekolek1000/wayvr-dashboard"
fetch.github = "olekolek1000/wayvr-dashboard"
cargo_lock = [ "src-tauri/Cargo.lock" ]

[wayvr-dashboard-git]
src.git = "https://github.com/olekolek1000/wayvr-dashboard"
fetch.github = "olekolek1000/wayvr-dashboard"
cargo_lock = [ "src-tauri/Cargo.lock" ]

[wayvr-dashboard-appimage]
src.github = "olekolek1000/wayvr-dashboard"
fetch.url = "https://github.com/olekolek1000/wayvr-dashboard/releases/download/$ver/wayvr-dashboard.AppImage"

[wayvr-dashboard-binary]
src.github = "olekolek1000/wayvr-dashboard"
fetch.url = "https://github.com/olekolek1000/wayvr-dashboard/releases/download/$ver/wayvr-dashboard"

[webfisher]
src.github = "PassiveLemon/webfisher"
fetch.github = "PassiveLemon/webfisher"

[webfisher-git]
src.git = "https://github.com/PassiveLemon/webfisher"
fetch.github = "PassiveLemon/webfisher"

[wivrn]
src.github = "WiVRn/WiVRn"
fetch.github = "WiVRn/WiVRn"

[wivrn-monado]
src.cmd = "curl https://api.github.com/repos/WiVRn/WiVRn/releases/latest | jq -r \".tag_name\" | xargs -I {} curl https://raw.githubusercontent.com/WiVRn/WiVRn/{}/monado-rev"
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"

[wivrn-git]
src.git = "https://github.com/WiVRn/WiVRn"
fetch.github = "WiVRn/WiVRn"

[wivrn-git-monado]
src.cmd = "curl https://raw.githubusercontent.com/WiVRn/WiVRn/refs/heads/master/monado-rev"
fetch.git = "https://gitlab.freedesktop.org/monado/monado.git"

[wlx-overlay-s]
src.github = "galister/wlx-overlay-s"
fetch.github = "galister/wlx-overlay-s"
cargo_lock = [ "Cargo.lock" ]

[wlx-overlay-s-git]
src.git = "https://github.com/galister/wlx-overlay-s"
fetch.github = "galister/wlx-overlay-s"
cargo_lock = [ "Cargo.lock" ]

[xrizer]
src.github = "Supreeeme/xrizer"
fetch.github = "Supreeeme/xrizer"
cargo_lock = [ "Cargo.lock" ]

[xrizer-git]
src.git = "https://github.com/Supreeeme/xrizer"
fetch.github = "Supreeeme/xrizer"
cargo_lock = [ "Cargo.lock" ]

