name: Cachix build
on:
  workflow_call:
    inputs:
      set:
        description: 'Package set (redist, nonredist)'
        required: true
        type: string
      type:
        description: 'Package type (release, tag, git)'
        required: true
        type: string

jobs:
  cachix-build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/runner-images/issues/2840
      # The Nix store and some builds can use a ton of space
    - name: Delete unused files to free disk space
      run: |
        sudo rm -rf \
          /opt/google/chrome \
          /opt/microsoft/msedge \
          /opt/microsoft/powershell \
          /opt/pipx \
          /usr/lib/mono \
          /usr/local/julia* \
          /usr/local/lib/android \
          /usr/local/lib/node_modules \
          /usr/local/share/chromium \
          /usr/local/share/powershell \
          /usr/share/dotnet \
          /usr/share/swift

    - name: Checkout code
      uses: actions/checkout@v6

    - name: Install packages
      run: |
        sudo apt-get install -y jq

    - name: Install nix
      uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Set up Cachix
      if: ${{ inputs.set == 'redistributable' }}
      uses: cachix/cachix-action@v17
      with:
        name: passivelemon
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      # x86_64-linux is currently the only supported architecture
    - name: Build packages for Cachix
      run: |
        nix eval .#CIPackageSets.x86_64-linux.${{ inputs.set }}.${{ inputs.type }} --json | jq '.[]' | xargs -rI {} nix build .#{} --keep-going --max-jobs 1 --cores 0

